name: GitHub Actions Demo

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automaticly triggered by a ${{ github.event_name}} event."

      - name: Pull repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build output
        uses: actions/upload-artifact@v4
        with:
          name: my-executable-program
          path: ./**
